version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "s3-notification-service"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "s3-notification-service-dev"
s3_bucket = "s3-sns-dev-bkt"
s3_prefix = "s3-notification-service-dev"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "s3-notification-service-prod"
s3_bucket = "s3-sns-prod-bkt"
s3_prefix = "s3-notification-service-prod"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"