version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "file-upload-notification-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "file-upload-notification-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=dev EmailSubscription=example@example.com"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "file-upload-notification-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "file-upload-notification-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=dev EmailSubscription=example@example.com"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "file-upload-notification-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "file-upload-notification-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=prod EmailSubscription=example@example.com"