# samconfig.toml
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "s3-lambda-sns-notification"

[default.build]
[default.build.parameters]
use_container = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[dev]
[dev.deploy]
[dev.deploy.parameters]
parameter_overrides = "Environment=dev"
stack_name = "s3-lambda-sns-notification-dev"

[prod]
[prod.deploy]
[prod.deploy.parameters]
parameter_overrides = "Environment=prod"
stack_name = "s3-lambda-sns-notification-prod"