version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-sns-notify-dev"
s3_prefix = "s3-sns"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "Environment=dev"

[prod.deploy.parameters]
stack_name = "s3-sns-notify-prod"
parameter_overrides = "Environment=prod"