AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  S3 to SNS email notification using AWS Lambda and AWS SAM (Node.js 22)

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 10
    MemorySize: 128
    Architectures:
      - x86_64

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

Resources:

  S3UploadBucket:
    Type: AWS::Serverless::SimpleTable
    Properties:
      BucketName: !Sub "upload-bucket-${Environment}-${AWS::AccountId}"

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "UploadNotificationTopic-${Environment}"

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: "nullstead@gmail.com"
      TopicArn: !Ref NotificationTopic

  S3NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "S3NotificationFunction-${Environment}"
      CodeUri: src/
      Handler: handler.main
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref S3UploadBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - S3ReadPolicy:
            BucketName: !Ref S3UploadBucket

Outputs:
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref S3UploadBucket
  FunctionName:
    Description: "Lambda function name"
    Value: !Ref S3NotificationFunction
  SNSTopic:
    Description: "SNS Topic ARN"
    Value: !Ref NotificationTopic
