# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Event-driven architecture with S3, Lambda, and SNS

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment

  NotificationEmail:
    Type: String
    Description: Email address to subscribe to SNS notifications
    Default: nullstead@gmail.com

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Timeout: 30
    MemorySize: 128
    Tracing: Active

Resources:
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'file-upload-notification-${Environment}'
      DisplayName: 'S3 Upload Notifications'

  EmailNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref NotificationEmail

  ProcessUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: processUpload.handler
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProcessUploadFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub 'arn:aws:s3:::file-upload-notification-${Environment}-${AWS::AccountId}'

  UploadBucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaPermission
    Properties:
      BucketName: !Sub 'file-upload-notification-${Environment}-${AWS::AccountId}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ProcessUploadFunction.Arn

Outputs:
  UploadBucketName:
    Description: S3 bucket for file uploads
    Value: !Ref UploadBucket
    
  UploadBucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt UploadBucket.Arn
    
  LambdaFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ProcessUploadFunction.Arn
    
  NotificationTopicArn:
    Description: SNS Topic ARN for notifications
    Value: !Ref NotificationTopic