AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  S3-to-SNS Notification Service
  An event-driven architecture that sends email notifications when files are uploaded to S3

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment type (development or production)
  
  EmailSubscription:
    Type: String
    Description: Email address to receive notifications
    Default: john.kponyo@amalitech.com

Mappings:
  EnvironmentMap:
    dev:
      BucketNameSuffix: -dev
    prod:
      BucketNameSuffix: -prod

Resources:
  # S3 bucket for file uploads - NOTIFICATION CONFIGURATION REMOVED TO BREAK CIRCULAR DEPENDENCY
  FileUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub:
          - 'file-uploads-${AWS::AccountId}${Suffix}'
          - Suffix: !FindInMap [EnvironmentMap, !Ref Environment, BucketNameSuffix]
      # NotificationConfiguration removed to break circular dependency

  # Lambda function to process S3 events
  FileUploadProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'file-upload-processor-${Environment}'
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Handler: app.handler
      CodeUri: ./src/
      Description: Processes S3 upload events and sends notifications via SNS
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
          ENVIRONMENT: !Ref Environment
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - S3ReadPolicy:
            BucketName: !Ref FileUploadBucket

  # Lambda permission to allow S3 to invoke our function
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FileUploadProcessor
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub:
          - 'arn:aws:s3:::file-uploads-${AWS::AccountId}${Suffix}'
          - Suffix: !FindInMap [EnvironmentMap, !Ref Environment, BucketNameSuffix]

  # SNS Topic for notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'file-upload-notifications-${Environment}'
      DisplayName: !Sub 'File Upload Notifications (${Environment})'

  # Email subscription to the SNS topic
  EmailNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref EmailSubscription
      
  # Use a custom resource to configure the S3 bucket notification after all resources are created
  S3NotificationCustomResource:
    Type: Custom::S3BucketNotification
    DependsOn: 
      - LambdaInvokePermission  # Only keep this explicit dependency
    Properties:
      ServiceToken: !Ref BucketNotificationFunction
      BucketName: !Ref FileUploadBucket  # This creates implicit dependency on FileUploadBucket
      NotificationConfiguration:
        LambdaFunctionConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt FileUploadProcessor.Arn  # This creates implicit dependency on FileUploadProcessor

  # Lambda function to handle the custom resource for S3 bucket notifications
  BucketNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'bucket-notification-handler-${Environment}'
      Runtime: nodejs22.x
      Handler: notification-handler.handler
      CodeUri: ./src/
      Description: Handles S3 bucket notification configuration
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:PutBucketNotification'
                - 's3:PutBucketNotificationConfiguration'  # Added this permission as well
              Resource: 
                Fn::Sub:
                  - 'arn:aws:s3:::file-uploads-${AWS::AccountId}${Suffix}'
                  - Suffix: !FindInMap [EnvironmentMap, !Ref Environment, BucketNameSuffix]

Outputs:
  FileUploadBucketName:
    Description: "Name of the S3 bucket for file uploads"
    Value: !Ref FileUploadBucket

  FileUploadBucketArn:
    Description: "ARN of the S3 bucket for file uploads"
    Value: !GetAtt FileUploadBucket.Arn
  
  NotificationTopicArn:
    Description: "ARN of the SNS topic for notifications"
    Value: !Ref NotificationTopic
  
  LambdaFunctionArn:
    Description: "ARN of the Lambda function"
    Value: !GetAtt FileUploadProcessor.Arn