name: Deploy SAM Application

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Install dependencies
        run: |
          cd src
          npm install
      
      - name: Determine environment
        id: determine-env
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "s3_bucket=s3-sns-prod-bkt" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "s3_bucket=s3-sns-dev-bkt" >> $GITHUB_OUTPUT
          fi
      
      - name: Build SAM application
        run: |
          sam build
          
      - name: Deploy to AWS (dev environment)
        if: steps.determine-env.outputs.environment == 'dev'
        run: |
          sam deploy \
            --stack-name s3-notification-service-dev \
            --s3-bucket ${{ steps.determine-env.outputs.s3_bucket }} \
            --parameter-overrides \
              Environment=dev \
              AdminEmail=${{ secrets.ADMIN_EMAIL_DEV }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
      
      - name: Deploy to AWS (prod environment)
        if: steps.determine-env.outputs.environment == 'prod'
        run: |
          sam deploy \
            --stack-name s3-notification-service-prod \
            --s3-bucket ${{ steps.determine-env.outputs.s3_bucket }} \
            --parameter-overrides \
              Environment=prod \
              AdminEmail=${{ secrets.ADMIN_EMAIL_PROD }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset