name: Deploy SAM App

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Install Dependencies
        run: npm install
        working-directory: src

      - name: Build SAM App
        run: sam build

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            sam deploy --guided --resolve-s3 --config-env prod
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            sam deploy --guided --resolve-s3 --config-env default
          else
            echo "Branch not set for deployment."
            exit 1
          fi
